memory_limit=64M
max_execution_time=30
max_input_time=60
post_max_size=8M
upload_max_filesize=8M
expose_php=Off
display_errors=Off
log_errors=On
error_log=/proc/self/fd/2

[opcache]
opcache.enable=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.validate_timestamps=0
opcache.save_comments=1
opcache.fast_shutdown=1

[apcu]
apc.enabled=1
apc.shm_size=64M
apc.enable_cli=1
