author = "Ryan Hendrickson"
base_url = "https://www.ryanjh.com"
description = "Articles on software engineering, platform engineering, and infrastructure by Ryan Hendrickson."
exclude_paginated_pages_in_sitemap = "all"
generate_feeds = true
taxonomies = [
    { name = "tags", feed = true },
]
title = "Ryan Hendrickson"

[markdown]
external_links_target_blank = true
lazy_async_image = true
render_emoji = true

[markdown.highlighting]
error_on_missing_language = true
theme = "catppuccin-mocha"

[search]
include_date = true
include_description = true

[extra]
# Put all your custom variables here
default_meta_description = "The homepage of Ryan Hendrickson's website."
