# Production yml file for https://www.ryanjh.com
services:
  caddy:
    image: caddy:2-alpine
    container_name: ryanjh_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # HTTP/3
    volumes:
      - /srv/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - /var/www/ryanjh:/var/www/ryanjh:ro
      - caddy_data:/data
      - caddy_logs:/var/log/caddy

volumes:
  caddy_data:
  caddy_logs:
