<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251118042915 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the "job" table for storing employment history';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE job (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              title TEXT NOT NULL,
              employer TEXT NOT NULL,
              location TEXT NOT NULL,
              description TEXT DEFAULT NULL,
              employment_type TEXT NOT NULL,
              start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE job');
    }
}
