<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251211032528 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the "user" table.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE "user" (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              email TEXT NOT NULL,
              roles JSONB NOT NULL,
              password TEXT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL
        );
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE "user"');
    }
}
